version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_loan_spring
    environment:
      POSTGRES_USER: loan_user
      POSTGRES_PASSWORD: loan_password
      POSTGRES_DB: loan
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
